### ISSUE TITLE
Support for .env files

### ISSUE THREAD

**Issue by alexdesignworks** [ahoy-cli/ahoy#64]
Maybe Ahoy already supports this, but it would be very helpful to automatically load environment variables from `.env` files. Or even better - implement what `Makefile` allows - including script from multiple files using `include` command.

**Comment by alexdesignworks** [comment]
Answering my own question:

```
entrypoint:
- bash
- "-c"
- |
  export $(grep -v '^#' .env | xargs)
  [ -f .env.local ] && export $(grep -v '^#' .env.local | xargs)
  bash -c "$0" "$@"
- '{{cmd}}'
- '{{name}}'
```

This allows to use `.env` and optional `.env.local` files with comments starting with `#`.

**Comment by frankcarey** [comment]
yes, this is basically the use-case for why I added `entrypoint` to provide for that flexibility. You could call `source` on the first line of a command I think as well, but then you need to do that repeatedly for every command.  I'm open to discussing a useful way to make this easier to do.

**Comment by alexdesignworks** [comment]
Updated version with failing flags and better `.env` and `.env.local` discovery
```
entrypoint:
  - bash
  - "-c"
  - "-e"
  - |
    [ -f .env ] && [ -s .env ] && export $(grep -v '^#' .env | xargs) && if [ -f .env.local ] && [ -s .env.local ]; then export $(grep -v '^#' .env.local | xargs); fi
    bash -e -c "$0" "$@"
  - '{{cmd}}'
  - '{{name}}'

```

**Comment by kevinquillen** [comment]
This works quite well. I ran into an issue however when I wanted to add a variable with a space in the value. The space and anything after wound up being stripped out. The most I could gather from much searching was how shells and xargs parse these out, but couldn't figure out how to get it to respect them with the above approach.

The variable holds the command I want to execute in Ahoy. If mutagen exists, use mutagen instead of docker-compose. The idea is that regardless of if mutagen is installed on the dev machine or not, the project will at least boot otherwise. Perhaps a tad unconventional, but I got around it by moving the above into a shell script:

```
#!/usr/bin/env bash
if ! command -v mutagen &> /dev/null; then
  export DOCKER_COMMAND="docker-compose"
else
  export DOCKER_COMMAND="mutagen compose"
fi

if [ -f .env ] && [ -s .env ]; then
  export $(grep -v '^#' .env | xargs )
fi

if [ -f .env.local ] && [ -s .env.local ]; then
  export $(grep -v '^#' .env.local | xargs )
fi

bash -e -c "$@"
```

Then in .ahoy.yml:

```
entrypoint:
  - ./.docker/entrypoint.sh
  - '{{cmd}}'
  - '{{name}}'
```

Everything started working then. Example ahoy command:

```
  up:
    cmd: |
      echo "Starting up containers..."
      ${DOCKER_COMMAND} pull
      ${DOCKER_COMMAND} up -d --remove-orphans
    usage: Create and start the default containers.
```

**Comment by AlexSkrypnyk** [comment]
an updated version that respects existing environment variables
```
    t=$(mktemp) && export -p > "$t" && set -a && . ./.env && if [ -f ./.env.local ];then . ./.env.local;fi && set +a && . "$t" && rm "$t" && unset t
```
